version: "3.9"

services:

  process-automation-modeler:
    image: ${PROCESS_AUTOMATION_MODELER_IMAGE}
    ports:
      - 8092:8092 # HTTP
    environment:
      - NAPPL_HOST=application-layer
      - NAPPL_PORT=8080
      - NAPPL_INSTANCE=nscalealinst1
      - NAPPL_SSL=false
      #- DEBUG=*
    networks:
      - nscale
    depends_on:
      - application-layer
