
services:

  application-layer-da:
    image: ${APPLICATION_LAYER_IMAGE}
    networks:
      - nscale
    depends_on:
      application-layer:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |  
       echo "initialize Document Area $${DOCUMENT_AREA:-DA}";
       java -jar ./al-cmdclient-*.jar -host application-layer run-cfg-method -method lockSystem;
       java -jar ./al-cmdclient-*.jar -host application-layer scenario-da -da $${DOCUMENT_AREA:-DA} -displayname $${DOCUMENT_AREA:-DA} -rs host=rendition-server -sl host=storage-layer;
       java -jar ./al-cmdclient-*.jar -host application-layer run-cfg-method -method unlockSystem;
       echo "done";
