version: "3.5"

volumes:
  pipeliner_data: {}
  pipeliner_config: {}
  
services:
  pipeliner:
    image: ${PIPELINER_IMAGE}
    hostname: ${CONTAINER_HOSTNAME}
    networks:
      - nscale
    volumes:
      - ./workdir/data:/opt/ceyoniq/nscale-pipeliner/workdir/data:rw
      #- ./workdir/config/cold.xml:/opt/ceyoniq/nscale-pipeliner/workdir/config/runtime/cold.xml:ro
      - ${PIPELINER_LICENSE_FILE}:/opt/ceyoniq/nscale-pipeliner/workdir/license.xml:ro
    depends_on:
      - application-layer
      - storage-layer
