version: "3.5"

services:

  application-layer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application.rule=PathPrefix(`/nscalealinst1`) || PathPrefix(`/res/`) || Path(`/engine.properties`) || Path(`/index.html`)"
      - "traefik.http.routers.application.entrypoints=web"
      - "traefik.http.services.application.loadbalancer.server.port=8080"

  application-layer-web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_root.rule=Path(`/`)"
      - "traefik.http.routers.web_root.entrypoints=web"
      - "traefik.http.middlewares.web_root.addprefix.prefix=/nscale_web"
      - "traefik.http.routers.web_root.middlewares=web_root"
      - "traefik.http.routers.web.rule=PathPrefix(`/nscale_web`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=8090"

  console:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.console.rule=PathPrefix(`/console`)"
      - "traefik.http.routers.console.entrypoints=web"
      - "traefik.http.services.console.loadbalancer.server.port=8086"

  administrator:
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.rap.rule=PathPrefix(`/rapadm`)"
      - "traefik.http.routers.rap.entrypoints=web"
      - "traefik.http.services.rap.loadbalancer.server.port=8080"

  traefik:
    image: ${TRAEFIK_IMAGE}
    container_name: traefik
    command:
      - "--api=false"       
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--log.level=DEBUG" # Enable debugging
      # - "--api.insecure=true"       
    ports:
      - "${TRAEFIK_EXTERNAL_HTTP_PORT}:80"
      # - "9090:8080" # Enable the Traefik Dashboard (set --api=true and --api.insecure=true)      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - nscale