
volumes:
  pipeliner_data: {}
  pipeliner_config: {}
  
services:
  pipeliner:
    image: ${PIPELINER_IMAGE}
    networks:
      - nscale
    volumes:
      - ./pipeliner/workdir/data:/opt/ceyoniq/nscale-pipeliner/workdir/data:rw
      - ./pipeliner/workdir/config/runtime/cold.xml:/opt/ceyoniq/nscale-pipeliner/workdir/config/runtime/cold.xml:ro
      - ./pipeliner/setup.sh:/setup.sh:ro
      - ${PIPELINER_LICENSE_FILE}:/opt/ceyoniq/nscale-pipeliner/workdir/license.xml:ro
    depends_on:
      - application-layer
      - storage-layer
    ports:
      - "4173:4173"
