version: "3.5"

networks:
  nscale:

volumes:
  postgresql_data: {}
  storage-layer_arc: {}
  storage-layer_da: {}
  storage-layer_etc: {}
  storage-layer_hd: {}
  rendition-server_share: {}
  monitoring-console_workspace: {}

services:
  postgresql:
    image: ${POSTGRESQL_IMAGE}
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./config/postgresql/0_setup.sh:/docker-entrypoint-initdb.d/0_setup.sh
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password # environment variable when running the image for the first time
      - NSCALE_USERNAME=nscale
      - NSCALE_DATABASE=nscale
      - NSCALE_PASSWORD=password
    networks:
      - nscale

  storage-layer:
    image: ${STORAGE_LAYER_IMAGE}
    stop_signal: SIGTERM
    volumes:
      - storage-layer_hd:/mnt
      - storage-layer_arc:/opt/ceyoniq/nscale-server/storage-layer/arc
      - storage-layer_da:/opt/ceyoniq/nscale-server/storage-layer/da
      - storage-layer_etc:/opt/ceyoniq/nscale-server/storage-layer/etc
      - ${STORAGE_LAYER_LICENSE_FILE}:/opt/ceyoniq/nscale-server/storage-layer/etc/license.xml:ro
    environment:
      - LOG_APPENDER=Console
    networks:
      - nscale

  application-layer:
    image: ${APPLICATION_LAYER_IMAGE}
    volumes:
      - ${APPLICATION_LAYER_LICENSE_FILE}:/opt/ceyoniq/nscale-server/application-layer/conf/license.xml:ro
    environment:
      - INSTANCE1_INSTANCE_LOGGER_CONF=instance1-log.xml
      - INSTANCE1_CORE_DB_DIALECT=PostgreSQL
      - INSTANCE1_CORE_DB_DRIVERCLASS=org.postgresql.Driver
      - INSTANCE1_CORE_DB_URL=jdbc:postgresql://postgresql:5432/nscale?loggerLevel=OFF
      - INSTANCE1_CORE_DB_USERNAME=nscale
      - INSTANCE1_CORE_DB_PASSWORD=password # Do not use this password in production!
      - INSTANCE1_CORE_DB_SCHEMA=public
      - JAVA_OPTS=-Xmx2g
      - INSTANCE1_CORE_FULLTEST_INDEX_MIRROR_LOCALCACHE=off
    networks:
      - nscale
    depends_on:
      - postgresql
      - storage-layer

  application-layer-web:
    image: ${APPLICATION_LAYER_WEB_IMAGE}
    environment:
      - NSCALE_HOST=application-layer
      - NSCALE_PORT=8080
      - NSCALE_INSTANCE=nscalealinst1
      - NSCALE_SSL=false
      - LOG4JCONFIGLOCATION=../conf/nscale_stdout_log_conf.xml
      - JAVA_OPTS=-Xmx2g
    networks:
      - nscale

  console:
    image: ${CONSOLE_IMAGE}
    environment:
      - LOG_APPENDER=Console
      - HOSTNAME=application-layer
      - PORT=8080
      - NAPPL_SSL=0
      - ALINSTANCE=nscalealinst1
    networks:
      - nscale

  monitoring-console:
    image: ${MONITORING_CONSOLE_IMAGE}
    stop_signal: SIGTERM
    volumes:
      - monitoring-console_workspace:/opt/ceyoniq/nscale-monitoring/workspace:rw
      - ${MONITORING_CONSOLE_LICENSE_FILE}:/opt/ceyoniq/nscale-monitoring/workspace/license.xml:ro
    environment:
      - MC_APPENDER=Console
      - MC_PASSWORD=admin
      - JAVA_OPTS=-Xmx1g -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.rmi.object.trustURLCodebase=false -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
    networks:
      - nscale

  rendition-server:
    image: ${RENDITION_SERVER_IMAGE}
    volumes:
      - rendition-server_share:/opt/ceyoniq/nscale-rendition-server/share:rw
      - ${RENDITION_SERVER_LICENSE_FILE}:/opt/ceyoniq/nscale-rendition-server/conf/license.xml:ro
    environment:
      - RSX_APPENDER=Console
      - RSX_PASSWORD=admin
      - JAVA_OPTS=-Xmx2g -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.rmi.object.trustURLCodebase=false -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
    networks:
      - nscale

  administrator:
    image: ${ADMINISTRATOR_IMAGE}
    environment:
      - APPLICATION_LAYER_HOST=application-layer
      - APPLICATION_LAYER_PORT=8080
      - APPLICATION_LAYER_INSTANCE=nscalealinst1
      - APPLICATION_LAYER_SSL=false
    networks:
      - nscale
