
services:

  application-layer-da:
    image: ${APPLICATION_LAYER_IMAGE}
    networks:
      - nscale
    depends_on:
      application-layer:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
       sleep 3;
       echo "initialize Document Area 'DA'";
       java -jar ./al-cmdclient-*.jar -host application-layer run-cfg-method -method lockSystem;
       java -jar ./al-cmdclient-*.jar -host application-layer scenario-da -da DA -displayname DA -rs host=rendition-server -sl host=storage-layer;
       java -jar ./al-cmdclient-*.jar -host application-layer run-cfg-method -method unlockSystem;
       echo "done";
