apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-layer-web
spec:
  template:
    spec:
      containers:
      - name: application-layer-web
        securityContext:
          runAsUser: 10001

