apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-ilm-connector
spec:
  template:
    spec:
      containers:
      - name: erp-ilm-connector
        securityContext:
          runAsUser: 10001
