apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-cmis-connector
spec:
  template:
    spec:
      containers:
      - name: erp-cmis-connector
        securityContext:
          runAsUser: 10001
