apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
      initContainers:
      - name: wait-for-application-layer
        securityContext:
          runAsUser: 10001
      containers:
      - name: pipeliner
        securityContext:
          runAsUser: 10001
