apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilm-connector
spec:
  template:
    spec:
      containers:
      - name: ilm-connector
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
