apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-application-layer
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: pipeliner
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
