apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-ilm-connector
spec:
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: erp-ilm-connector
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway 
