apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-connector
spec:
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: webdav-connector
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway 
