---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator
spec:
  template:
    spec:
      containers:
      - name: administrator
        resources:
          limits:
            cpu: "2000m"
            memory: "1300Mi"
            ephemeral-storage: "800Mi"
          requests:
            cpu: "500m"
            memory: "700Mi"
            ephemeral-storage: "700Mi"
