apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-database
        resources:
          limits:
            cpu: "50m"
            memory: "50Mi"
            ephemeral-storage: "0Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
            ephemeral-storage: "0Mi"           
      containers:
      - name: application-layer
        resources:
          limits:
            cpu: "3000m"
            memory: "4000Mi"
            ephemeral-storage: "900Mi"
          requests:
            cpu: "300m"
            memory: "1000Mi"
            ephemeral-storage: "800Mi"
