apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-ilm-connector
spec:
  template:
    spec:
      containers:
      - name: erp-ilm-connector
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "300m"
            memory: "500Mi"
            ephemeral-storage: "400Mi"
