apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-application-layer
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: "300Mi"
      containers:
      - name: pipeliner
        resources:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
            ephemeral-storage: "300Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
            ephemeral-storage: "300Mi"
