apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "200m"
            memory: "400Mi"
            ephemeral-storage: "250Mi"
