apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendition-server
spec:
  template:
    spec:
      containers:
      - name: rendition-server
        resources:
          limits:
            cpu: "2000m"
            memory: "2000Mi"
            ephemeral-storage: "1300Mi"
          requests:
            cpu: "600m"
            memory: "1000Mi"
            ephemeral-storage: "1000Mi"
