apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-layer
spec:
  template:
    spec:
      initContainers:
      - name: storage-layer-conf
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: "250Mi"
      containers:
      - name: storage-layer
        resources:
          limits:
            cpu: "500m"
            memory: "1000Mi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: "250Mi"
