apiVersion: apps/v1
kind: Deployment
metadata:
  name: xta-connector
spec:
  template:
    spec:
      containers:
      - name: xta-connector
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
            ephemeral-storage: "550Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
            ephemeral-storage: "450Mi"
