{
 "title": "CAdvisor - Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Concentration" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_application-layer_.\"} > bool 0) + 8",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_application-layer-web_.\"} > bool 0) + 7",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_console_.\"} > bool 0) + 6",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_rendition-server_.\"} > bool 0) + 5",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_monitoring-console_.\"} > bool 0) + 4",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_postgresql_.\"} > bool 0) + 3",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_storage-layer_.\"} > bool 0) + 2",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(container_start_time_seconds{name=~\"nscale_rms_.\"} > bool 0) + 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{name=~\".*nscale.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*nscale.*\"}[5m])) by (id,name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network received [bytes/second]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*nscale.*\"}[5m])) by (id,name)"
    }
   ]
  },
  {
   "title": "Network transmitted [bytes/second]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*nscale.*\"}[5m])) by (id,name)"
    }
   ]
  },
  {
   "title": "Disk reads [bytes/second]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".*nscale.*\"}[5m])) by (id,name)\r"
    }
   ]
  },
  {
   "title": "Disk writes [bytes/second]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".*nscale.*\"}[5m])) by (id,name)\r"
    }
   ]
  }
 ]
}