apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-layer-web
spec:
  scaleTargetRef:
    kind: Deployment
    name: application-layer-web
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
