apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rendition-server
spec:
  scaleTargetRef:
    kind: Deployment
    name: rendition-server
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
