#!/usr/bin/env bash
set -e

PGPASSWORD="$POSTGRESQL_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USERNAME" postgres <<-EOSQL
  CREATE DATABASE ${NSCALE_DATABASE} ENCODING 'UTF8';

  CREATE USER ${NSCALE_USERNAME} WITH ENCRYPTED PASSWORD '${NSCALE_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${NSCALE_DATABASE} TO ${NSCALE_USERNAME};

  --ALTER DATABASE nscale SET log_error_verbosity to 'TERSE';
  CREATE EXTENSION fuzzystrmatch;
  CREATE EXTENSION pg_trgm;

EOSQL