apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nscale
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ceyoniq/container.git
        revision: HEAD
        directories:
          - path: kubernetes/kustomize/nscale/overlays/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/ceyoniq/container.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
