apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator
  labels:
    app: administrator
spec:
  selector:
    matchLabels:
      app: administrator
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: administrator
    spec:
      automountServiceAccountToken: false
      containers:
      - name: administrator
        image: ceyoniq.azurecr.io/release/nscale/administrator:ubi.9.3.1201
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /rapadm/
            port: administrator
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /rapadm/
            port: administrator
          initialDelaySeconds: 20
        env:
          - name: APPLICATION_LAYER_HOST
            value: "application-layer"
          - name: APPLICATION_LAYER_PORT
            value: "8080"
          - name: APPLICATION_LAYER_INSTANCE
            value: "nscalealinst1"
          - name: APPLICATION_LAYER_SSL
            value: "false"
          - name: JAVA_OPTIONS
            value: "-Dorg.eclipse.rap.rwt.settingStoreFactory=settings-per-user"
        ports:
        - containerPort: 8080
          name: administrator
---
apiVersion: v1
kind: Service
metadata:
  name: administrator
  labels:
    service: administrator
spec:
  ports:
  - port: 8080
    name: administrator
    targetPort: 8080
    appProtocol: http
  selector:
    app: administrator
