apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator
  labels:
    app: administrator
spec:
  selector:
    matchLabels:
      app: administrator
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: administrator
    spec:
      containers:
      - name: administrator
        image: ceyoniq.azurecr.io/release/nscale/administrator:8.3.1002.2022033119.641463842588
        imagePullPolicy: Always
        env:
          - name: APPLICATION_LAYER_HOST
            value: "application-layer"
          - name: APPLICATION_LAYER_PORT
            value: "8080"
          - name: APPLICATION_LAYER_INSTANCE
            value: "nscalealinst1"
          - name: APPLICATION_LAYER_SSL
            value: "false"
          - name: JAVA_OPTIONS
            value: "-Dorg.eclipse.rap.rwt.settingStoreFactory=settings-per-user"
        ports:
        - containerPort: 8080
          name: administrator
        resources:
          limits:
            cpu: "2000m"
            memory: "1300Mi"
          requests:
            cpu: "100m"
            memory: "700Mi"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: administrator
  labels:
    service: administrator
spec:
  ports:
  - port: 8080
    name: administrator
    targetPort: 8080
  selector:
    app: administrator
