apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
  labels:
    app: application-layer
spec:
  serviceName: application-layer
  selector:
    matchLabels:
      app: application-layer
  replicas: 1
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: application-layer
        ceyoniq.com/application-layer-cluster-name: "cluster1"
    spec:
      serviceAccountName: kubeping-svc-account
      imagePullSecrets:
      - name: regcred
      initContainers:
      # wait for database to be ready
      - name: check-db-ready
        image: bitnami/postgresql:14
        imagePullPolicy: Always
        command: ['sh', '-c',
          'until pg_isready -U postgres -h postgresql -p 5432;
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: application-layer
        image: ceyoniq.azurecr.io/release/nscale/application-layer:8.3.1501.2022082421.0
        imagePullPolicy: Always
        startupProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
        env:
          - name: INSTANCE1_INSTANCE_LOGGER_CONF
            value: "log4j/instance1-log.xml"
          - name: INSTANCE1_CORE_DB_DIALECT
            value: "PostgreSQL"
          - name: INSTANCE1_CORE_DB_DRIVERCLASS
            value: "org.postgresql.Driver"
          - name: INSTANCE1_CORE_DB_URL
            value: "jdbc:postgresql://postgresql:5432/nscale?loggerLevel=OFF"
          - name: INSTANCE1_CORE_DB_USERNAME
            value: "nscale"
          - name: INSTANCE1_CORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: INSTANCE1_CORE_DB_SCHEMA
            value: "public"
          - name: INITIALIZE_DOCUMENT_AREA
            value: "DA"
          - name: INSTANCE1_CLUSTER_CORE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INSTANCE1_CLUSTER_CORE_DESCRIPTION
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=50.0
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE1_CORE_FULLTEST_INDEX_MIRROR_LOCALCACHE
            value: "off"
        ports:
        - containerPort: 8080
          name: application
        resources:
          limits:
            cpu: "2000m"
            memory: "3000Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-server/application-layer/conf/license.xml
        - name: log4j
          mountPath: /opt/ceyoniq/nscale-server/application-layer/conf/log4j
        - name: logs
          mountPath: /opt/ceyoniq/nscale-server/application-layer/logs
        - name: temp
          mountPath: /opt/ceyoniq/nscale-server/application-layer/temp
      volumes:
      - name: license
        configMap:
          name: application-layer-license
      - name: log4j
        configMap:
          name: application-layer-log4j
      - name: logs
        emptyDir: {}
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: application-layer
  labels:
    app: application-layer
spec:
  ports:
  - port: 8080
    name: application
  clusterIP: None
  selector:
    app: application-layer
