apiVersion: batch/v1
kind: Job
metadata:
  name: application-layer-setup
  labels:
    app: application-layer-setup
spec:
  template:
    metadata:
      labels:
        app: application-layer-setup
    spec:
      hostname: application-layer-setup
      initContainers:
      - name: wait-for-application-layer
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
        - >
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://application-layer:8080/index.html)" != "200" ]]; do
            echo '.'
            sleep 5;
          done
      containers:
      - name: application-layer
        image: ceyoniq.azurecr.io/release/nscale/application-layer:8.4.1501.2023022808
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - >
          echo "initialize Document Area 'DA'"; 
          al -host application-layer run-cfg-method -method lockSystem;
          al -host application-layer scenario-da -da DA -displayname DA -rs host=rendition-server -sl host=storage-layer;
          al -host application-layer run-cfg-method -method unlockSystem;
          echo "done";
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
  backoffLimit: 1
