apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
  labels:
    app: application-layer
spec:
  serviceName: application-layer
  selector:
    matchLabels:
      app: application-layer
  replicas: 1
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: application-layer
        ceyoniq.com/application-layer-cluster-name: cluster1
    spec:
      serviceAccountName: kubeping-svc-account
      imagePullSecrets:
      - name: regcred
      initContainers:
      # wait for database to be ready
      - name: check-db-ready
        image: docker.io/bitnami/postgresql:15
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - >
          until pg_isready -U postgres -h postgresql -p 5432 -t 1; do
            echo '.';
            sleep 2;
          done
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: "300Mi"
      containers:
      - name: application-layer
        image: ceyoniq.azurecr.io/release/nscale/application-layer:ubi.9.0.1200.2023052021
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /index.html
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /jmx/status
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 1
        env:
          - name: INSTANCE1_INSTANCE_LOGGER_CONF
            value: "log4j/instance1-log.xml"
          - name: INSTANCE1_CORE_DB_DIALECT
            value: "PostgreSQL"
          - name: INSTANCE1_CORE_DB_DRIVERCLASS
            value: "org.postgresql.Driver"
          - name: INSTANCE1_CORE_DB_URL
            value: "jdbc:postgresql://postgresql:5432/nscale?loggerLevel=OFF"
          - name: INSTANCE1_CORE_DB_USERNAME
            value: "nscale"
          - name: INSTANCE1_CORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: INSTANCE1_CORE_DB_SCHEMA
            value: "public"
          - name: INSTANCE1_CLUSTER_CORE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE1_CLUSTER_CORE_DESCRIPTION
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=50.0
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE1_CORE_FULLTEST_INDEX_MIRROR_LOCALCACHE
            value: "off"
        ports:
        - containerPort: 8080
          name: application
        resources:
          limits:
            cpu: "2000m"
            memory: "3000Mi"
            ephemeral-storage: "900Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
            ephemeral-storage: "800Mi"
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-server/application-layer/conf/license.xml
        - name: log4j
          mountPath: /opt/ceyoniq/nscale-server/application-layer/conf/log4j
        - name: logs
          mountPath: /opt/ceyoniq/nscale-server/application-layer/logs
        - name: temp
          mountPath: /opt/ceyoniq/nscale-server/application-layer/temp
        - name: podinfo
          mountPath: /etc/podinfo
      terminationGracePeriodSeconds: 100
      volumes:
      # https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      - name: license
        configMap:
          name: license
      - name: log4j
        configMap:
          name: application-layer-log4j
      - name: logs
        emptyDir:
          sizeLimit: 2Mi
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: application-layer
  labels:
    app: application-layer
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    name: application
    appProtocol: http
  selector:
    app: application-layer

---
apiVersion: batch/v1
kind: Job
metadata:
  name: application-layer-setup
  labels:
    app: application-layer-setup
spec:
  template:
    metadata:
      labels:
        app: application-layer-setup
    spec:
      hostname: application-layer-setup
      initContainers:
      - name: wait-for-application-layer
        image: docker.io/curlimages/curl:8.00.1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - >
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://application-layer:8080/index.html)" != "200" ]]; do
            echo '.'
            sleep 5;
          done
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "350Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: "300Mi"
      containers:
      - name: application-layer
        image: ceyoniq.azurecr.io/release/nscale/application-layer:ubi.9.0.1200.2023052021
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - >
          echo "initialize Document Area 'DA'";
          al -host application-layer run-cfg-method -method lockSystem;
          al -host application-layer scenario-da -da DA -displayname DA -rs host=rendition-server -sl host=storage-layer;
          al -host application-layer run-cfg-method -method unlockSystem;
          echo "done";
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
            ephemeral-storage: "900Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
            ephemeral-storage: "800Mi"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
  backoffLimit: 1
  #activeDeadlineSeconds: 180

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: application-layer
  labels:
    app: application-layer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: application-layer