apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmis-connector
  labels:
    app: cmis-connector
spec:
  selector:
    matchLabels:
      app: cmis-connector
  replicas: 1
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cmis-connector
    spec:
      containers:
      - name: cmis-connector
        image: nscale/cmis-connector:8.0.5000.2021032508.518926779920
        env:
        - name: CMIS_AL_HOST
          value: "application-layer"
        - name: CMIS_AL_PORT
          value: "8080"
        - name: CMIS_AL_SSL
          value: "0"
        - name: CMIS_AL_INSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"               
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/ceyoniq/nscale-cmis-connector/bin/readiness-probe.sh
          periodSeconds: 10
          initialDelaySeconds: 10
        ports:
        - containerPort: 8096
          name: cmis
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cmis-connector
  labels:
    service: cmis-connector
spec:
  ports:
  - port: 8096
    targetPort: 8096
    name: cmis
  selector:
    app: cmis-connector