apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmis-connector
  labels:
    app: cmis-connector
spec:
  selector:
    matchLabels:
      app: cmis-connector
  replicas: 0
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cmis-connector
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      containers:
      - name: cmis-connector
        image: ceyoniq.azurecr.io/release/nscale/cmis-connector:ubi.9.0.1202.2023052608
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /cmis/
            port: 8096
          initialDelaySeconds: 20
        env:
        - name: CMIS_AL_HOST
          value: "application-layer"
        - name: CMIS_AL_PORT
          value: "8080"
        - name: CMIS_AL_SSL
          value: "0"
        - name: CMIS_AL_INSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8096
          name: cmis
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
            ephemeral-storage: "550Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
            ephemeral-storage: "450Mi"
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-cmis-connector/temp/
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cmis-connector
  labels:
    service: cmis-connector
spec:
  ports:
  - port: 8096
    targetPort: 8096
    name: cmis
    appProtocol: http
  selector:
    app: cmis-connector
