apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  selector:
    matchLabels:
      app: console
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: nscale/console:8.0
        imagePullPolicy: Always
        env:
        - name: LOG_APPENDER
          value: "Console"
        - name: HostName
          value: "application-layer"
        - name: Port
          value: "8080"
        - name: NAPPL_SSL
          value: "0"
        - name: ALInstance
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"           
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/ceyoniq/nscale-server/console/bin/readiness-probe.sh
          periodSeconds: 10
          initialDelaySeconds: 10
        ports:
        - containerPort: 8086
          name: console
        resources:
          limits:
            cpu: "2000m"
            memory: "1300Mi"
          requests:
            cpu: "100m"
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    service: console
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: console
  selector:
    app: console