apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  selector:
    matchLabels:
      app: console
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: console
    spec:
      automountServiceAccountToken: false
      containers:
      - name: console
        image: ceyoniq.azurecr.io/release/nscale/console:ubi.10.0.1400.13395
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /console/systemConfiguration.xml
            port: console
          initialDelaySeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /console/
            port: console
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /console/systemConfiguration.xml
            port: console
        env:
        - name: LOG_APPENDER
          value: "Console"
        - name: HOSTNAME
          value: "application-layer"
        - name: PORT
          value: "8080"
        - name: NAPPL_SSL
          value: "0"
        - name: ALINSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8086
          name: console
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-server/console/temp
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    service: console
spec:
  ports:
  - port: 8086
    name: console
    appProtocol: http
  selector:
    app: console
