apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-cmis-connector
  labels:
    app: erp-cmis-connector
spec:
  selector:
    matchLabels:
      app: erp-cmis-connector
  replicas: 1
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: erp-cmis-connector
    spec:
      automountServiceAccountToken: false
      containers:
      - name: erp-cmis-connector
        image: ceyoniq.azurecr.io/release/nscale/erp-cmis-connector:ubi.10.0.1500.2025082510
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /erp-cmis/
            port: cmis
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /erp-cmis/
            port: cmis
          initialDelaySeconds: 20
        env:
        - name: CMIS_AL_HOST
          value: "application-layer"
        - name: CMIS_AL_PORT
          value: "8080"
        - name: CMIS_AL_SSL
          value: "0"
        - name: CMIS_AL_INSTANCE
          value: "nscalealinst1"
        - name: ERPCMIS_CONTEXT_PATH
          value: "/erp-cmis"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8096
          name: cmis
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-for-sap/erp-cmis/temp/
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: erp-cmis-connector
  labels:
    service: erp-cmis-connector
spec:
  ports:
  - port: 8096
    targetPort: 8096
    name: cmis
    appProtocol: http
  selector:
    app: erp-cmis-connector
