apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-ilm-connector
  labels:
    app: erp-ilm-connector
spec:
  selector:
    matchLabels:
      app: erp-ilm-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: erp-ilm-connector
    spec:
      automountServiceAccountToken: false
      containers:
      - name: erp-ilm-connector
        image: ceyoniq.azurecr.io/release/nscale/erp-ilm-connector:ubi.10.0.1000.2025032002
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /sap_ilm/
#            port: ilm
#            httpHeaders:
#            - name: Authorization
#              value: "Basic YW5vbjphbm9u"
#          initialDelaySeconds: 20
        env:
        - name: ILM_AL_HOST
          value: "application-layer"
        - name: ILM_AL_PORT
          value: "8080"
        - name: ILM_AL_SSL
          value: "0"
        - name: ILM_AL_INSTANCE
          value: "nscalealinst1"
        - name: ILM_AL_USER
          value: "admin"
        - name: ILM_AL_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8297
          name: ilm
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-for-sap/erp-connector-ilm/temp
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: erp-ilm-connector
  labels:
    service: erp-ilm-connector
spec:
  ports:
  - port: 8297
    targetPort: 8297
    name: ilm
    appProtocol: http
  selector:
    app: erp-ilm-connector
