apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilm-connector
  labels:
    app: ilm-connector
spec:
  selector:
    matchLabels:
      app: ilm-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ilm-connector
    spec:
      imagePullSecrets:
      - name: regcred    
      containers:
      - name: ilm-connector
        image: ceyoniq.azurecr.io/release/nscale/ilm-connector:8.0.5000.2021032309.777635089529
        env:
        - name: ILM_AL_HOST
          value: "application-layer"
        - name: ILM_AL_PORT
          value: "8080"
        - name: ILM_AL_SSL
          value: "0"
        - name: ILM_AL_INSTANCE
          value: "nscalealinst1"
        - name: ILM_AL_USER
          value: "admin"
        - name: ILM_AL_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"           
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
        ports:
        - containerPort: 8297
          name: ilm
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ilm-connector
  labels:
    service: ilm-connector
spec:
  ports:
  - port: 8297
    targetPort: 8297
    name: ilm
  selector:
    app: ilm-connector