apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  nscale.ceyoniq.com/version: "9"
  app.kubernetes.io/part-of: nscale
  version: v9.0.1202

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    nscale.ceyoniq.com: Copyright Ceyoniq GmbH

secretGenerator:
- name: postgresql
  literals:
  - postgresql-password=nscale

configMapGenerator:
- name: license
  files:
  - license.xml=license.xml
- name: postgresql-init-script
  files:
  - config/postgresql/0_setup.sh
- name: pipeliner-config
  files:
  - config/pipeliner/cold.xml
- name: pipeliner-setup
  files:
  - config/pipeliner/setup.sh
- name: application-layer-log4j
  files:
  - config/application-layer/instance1-log-console.conf
  - config/application-layer/instance1-log.xml
- name: application-layer-web-log4j
  files:
  - config/application-layer-web/nscale_stdout_log_conf.xml

resources:
- rbac.yaml
- postgresql.yaml
- application-layer.yaml
- storage-layer.yaml
- application-layer-web.yaml
- rendition-server.yaml
- administrator.yaml
- monitoring-console.yaml
- console.yaml
# Enable process automation modeler
#- process-automation-modeler.yaml
# Enable pipeliner
#- pipeliner.yaml
# Enable nscale connectors if required
#- cmis-connector.yaml
#- ilm-connector.yaml
#- webdav-connector.yaml
#- xta-connector.yaml
