apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    nscale.ceyoniq.com: Copyright Ceyoniq GmbH
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: nscale
    nscale.ceyoniq.com/version: "9"
    version: v9.1.1401

secretGenerator:
- literals:
  - postgresql-password=password
  - nscale-password=password
  name: postgresql

configMapGenerator:
- files:
  - license.xml=license.xml
  name: license
- files:
  - config/postgresql/0_setup.sh
  name: postgresql-init-script
- files:
  - config/pipeliner/cold.xml
  name: pipeliner-config
- files:
  - config/pipeliner/setup.sh
  name: pipeliner-setup
- files:
  - config/application-layer/instance1-log.xml
  name: application-layer-log4j
- files:
  - config/application-layer-web/nscale_stdout_log_conf.xml
  name: application-layer-web-log4j

resources:
- postgresql.yaml
- application-layer.yaml
- storage-layer.yaml
- application-layer-web.yaml
- rendition-server.yaml
- administrator.yaml
- monitoring-console.yaml
- console.yaml
- process-automation-modeler.yaml
- pipeliner.yaml
- cmis-connector.yaml
- ilm-connector.yaml
- webdav-connector.yaml
- xta-connector.yaml
