apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-console
  labels:
    app: monitoring-console
spec:
  selector:
    matchLabels:
      app: monitoring-console
  replicas: 1
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: monitoring-console
    spec:
      hostname: monitoring-console 
      containers:
      - name: monitoring-console
        image: nscale/monitoring-console:8.0
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/ceyoniq/nscale-monitoring/readiness-probe.sh
          periodSeconds: 10
          initialDelaySeconds: 10
        ports:
        - containerPort: 8387
          name: monitoring
        env:
        - name: MC_APPENDER
          value: Console
        - name: INITIALIZE_COMPOSE
          value: "true"
        - name: MC_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"           
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
        volumeMounts:
        - name: license
          mountPath: /opt/ceyoniq/nscale-monitoring/workspace/license.xml
          subPath: license.xml
      volumes:
      - name: license
        configMap:
          name: monitoring-console-license
      - name: monitoring-console-workspace
        persistentVolumeClaim:
          claimName: monitoring-console-workspace
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-console
  labels:
    app: monitoring-console
spec:
  ports:
  - port: 8387
    targetPort: 8387
    name: monitoring
  selector:
    app: monitoring-console