apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-console
  labels:
    app: monitoring-console
spec:
  selector:
    matchLabels:
      app: monitoring-console
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monitoring-console
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      initContainers:
      # The license file mount inside the workspace volume prevents the volume to get initialized with the image data.
      # Therefore we need to copy the data from the image to the volume manually before startup.
      - name: monitoring-console-conf
        image: ceyoniq.azurecr.io/release/nscale/monitoring-console:ubi.9.2.1001.2024032018
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          # Copy the configuration from the image into the volume on first startup.
          test -f /mnt/monitoring-config.properties ||
            cp -a /opt/ceyoniq/nscale-monitoring/workspace/* /mnt
        volumeMounts:
        - name: monitoring-console-workspace
          mountPath: /mnt
        resources:
          limits:
            cpu: "600m"
            memory: "800Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "400m"
            memory: "600Mi"
            ephemeral-storage: "400Mi"
      containers:
      - name: monitoring-console
        image: ceyoniq.azurecr.io/release/nscale/monitoring-console:ubi.9.2.1001.2024032018
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /nscalemc/
            port: 8387
          initialDelaySeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /nscalemc/
            port: 8387
        env:
        - name: MC_APPENDER
          value: Console
        - name: INITIALIZE_COMPOSE
          value: "true"
        - name: MC_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0 -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.rmi.object.trustURLCodebase=false -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false
        ports:
        - containerPort: 8387
          name: monitoring
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
            ephemeral-storage: "400Mi"
        volumeMounts:
        - name: monitoring-console-workspace
          mountPath: /opt/ceyoniq/nscale-monitoring/workspace
        - name: license
          mountPath: /opt/ceyoniq/nscale-monitoring/workspace/license.xml
          subPath: license.xml
      volumes:
      - name: license
        configMap:
          name: license
      - name: monitoring-console-workspace
        persistentVolumeClaim:
          claimName: monitoring-console-workspace
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-console
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/nscalemc/rest/metrics/nscale'
    prometheus.io/port: monitoring
    prometheus.openshift.io/password: ''
    prometheus.openshift.io/username: "anonymous"
  labels:
    app: monitoring-console
spec:
  ports:
  - port: 8387
    name: monitoring
    appProtocol: http
  selector:
    app: monitoring-console