apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-console
  labels:
    app: monitoring-console
spec:
  selector:
    matchLabels:
      app: monitoring-console
  replicas: 1
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: monitoring-console
    spec:
      imagePullSecrets:
      - name: regcred    
      initContainers:
      # The license file mount inside the workspace volume prevents the volume to get initialized with the image data.
      # Therefore we need to copy the data from the image to the volume manually before startup.
      - name: monitoring-console-conf
        image:  ceyoniq.azurecr.io/release/nscale/monitoring-console:8.0.5400.2021071218.1061909966281
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          # Copy the configuration from the image into the volume on first startup.
          test -f /mnt/monitoring-config.properties ||
            cp -a /opt/ceyoniq/nscale-monitoring/workspace/* /mnt
        volumeMounts:
        - name: monitoring-console-workspace
          mountPath: /mnt
      containers:
      - name: monitoring-console
        image: ceyoniq.azurecr.io/release/nscale/monitoring-console:8.0.5400.2021071218.1061909966281
        startupProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
          failureThreshold: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
        ports:
        - containerPort: 8387
          name: monitoring
        env:
        - name: MC_APPENDER
          value: Console
        - name: INITIALIZE_COMPOSE
          value: "true"
        - name: MC_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"           
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
        volumeMounts:
        - name: monitoring-console-workspace
          mountPath: /opt/ceyoniq/nscale-monitoring/workspace
        - name: license
          mountPath: /opt/ceyoniq/nscale-monitoring/workspace/license.xml
          subPath: license.xml
      volumes:
      - name: license
        configMap:
          name: monitoring-console-license          
      - name: monitoring-console-workspace
        persistentVolumeClaim:
          claimName: monitoring-console-workspace
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-console
  labels:
    app: monitoring-console
spec:
  ports:
  - port: 8387
    targetPort: 8387
    name: monitoring
  selector:
    app: monitoring-console