apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
  labels:
    app: pipeliner
spec:
  serviceName: pipeliner
  selector:
    matchLabels:
      app: pipeliner
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: pipeliner
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: wait-for-application-layer
        image: ceyoniq.azurecr.io/release/nscale/pipeliner:9.0.1003.2023032414.0
        imagePullPolicy: Always
        command: ['sh', '-c',
          'while [ $(curl -sw "%{http_code}" "http://application-layer:8080/index.html" -o /dev/null) -ne 200 ];
          do echo waiting for application layer; sleep 5; done;']
      containers:
      - name: pipeliner
        image: ceyoniq.azurecr.io/release/nscale/pipeliner:9.0.1003.2023032414.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/license.xml
        - name: config
          subPath: cold.xml
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/config/runtime/cold.xml
        - name: pipeliner-data
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/data
        - name: pipeliner-setup
          subPath: setup.sh
          mountPath: /setup.sh
      volumes:
      - name: license
        configMap:
          name: license
      - name: pipeliner-data
        persistentVolumeClaim:
          claimName: pipeliner-data
      - name: config
        configMap:
          name: pipeliner-config
      - name: pipeliner-setup
        configMap:
          name: pipeliner-setup
  volumeClaimTemplates:
  - metadata:
      name: pipeliner-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pipeliner
spec:
  ports:
  - port: 4173
    name: pipeliner
  selector:
    app: pipeliner