apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
  labels:
    app: pipeliner
spec:
  serviceName: pipeliner
  selector:
    matchLabels:
      app: pipeliner
  replicas: 1
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: pipeliner
    spec:
      imagePullSecrets:
      - name: regcred    
      containers:
      - name: pipeliner    
        image: ceyoniq.azurecr.io/release/nscale/pipeliner:8.0.5400.2021071612.806457530597
        resources:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        startupProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
          failureThreshold: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/license.xml
        - name: config
          subPath: cold.xml
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/config/runtime/cold.xml
        - name: pipeliner-data
          mountPath: /opt/ceyoniq/nscale-pipeliner/workdir/data
        - name: pipeliner-setup
          subPath: setup.sh
          mountPath: /setup.sh    
      volumes:
      - name: license
        configMap:
          name: pipeliner-license
      - name: pipeliner-data
        persistentVolumeClaim:
          claimName: pipeliner-data
      - name: config
        configMap:
          name: pipeliner-config
      - name: pipeliner-setup
        configMap:
          name: pipeliner-setup
---
apiVersion: v1
kind: Service
metadata:
  name: pipeliner
spec:
  ports:
  - port: 4173
    name: pipeliner
  selector:
    app: pipeliner