---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
      role: master
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
        role: master
    spec:
      automountServiceAccountToken: false
      containers:
      - name: postgresql
        image: docker.io/bitnamilegacy/postgresql:17
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432 -t 1
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              pg_isready -U "postgres" -h 127.0.0.1 -p 5432 -t 1
              [ -f /opt/bitnami/postgresql/tmp/.initialized ]
        env:
#        - name: POSTGRESQL_EXTRA_FLAGS
#          value: "-c log_statement=all"
        - name: BITNAMI_DEBUG
          value: "false"
        - name: POSTGRESQL_USERNAME
          value: "postgres"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgresql-password
        - name: NSCALE_USERNAME
          value: "nscale"
        - name: NSCALE_DATABASE
          value: "nscale"
        - name: NSCALE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: nscale-password
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d/
        - name: postgresql-db
          mountPath: /bitnami/postgresql
      volumes:
      - name: custom-init-scripts
        configMap:
          name: postgresql-init-script
      - name: postgresql-db
        persistentVolumeClaim:
          claimName: postgresql-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
    appProtocol: tcp
  selector:
    app: postgresql
