apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-automation-modeler
  labels:
    app: process-automation-modeler
spec:
  selector:
    matchLabels:
      app: process-automation-modeler
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: process-automation-modeler
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      containers:
      - name: process-automation-modeler
        image: ceyoniq.azurecr.io/release/nscale/process-automation-modeler:ubi.9.1.1400.20803
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /modeler
            port: 8092
          initialDelaySeconds: 30
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /modeler
            port: 8092
          periodSeconds: 10
          timeoutSeconds: 1
        env:
        - name: NSCALE_HOST
          value: "application-layer"
        - name: NSCALE_PORT
          value: "8080"
        - name: NSCALE_SSL
          value: "false"
        - name: NSCALE_INSTANCE
          value: "nscalealinst1"
        - name: NSCALE_SSL
          value: "false"
        ports:
        - containerPort: 8092
          name: modeler
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: process-automation-modeler
  labels:
    service: process-automation-modeler
spec:
  ports:
  - port: 8092
    targetPort: 8092
    name: modeler
    appProtocol: http
  selector:
    app: process-automation-modeler
