apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendition-server
  labels:
    app: rendition-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rendition-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8192'
      labels:
        app: rendition-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: rendition-server
        image: ceyoniq.azurecr.io/release/nscale/rendition-server:ubi.9.3.1001.2024092712
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /rs/
            port: 8192
          initialDelaySeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /rs/
            port: 8192
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /rs/
            port: 8192
        env:
        - name: RSX_APPENDER
          value: Console
        - name: RSX_PASSWORD
          value: "admin"
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0 -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.rmi.object.trustURLCodebase=false -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false -Duser.country=DE -Duser.language=de
        volumeMounts:
        - name: license
          mountPath: /opt/ceyoniq/nscale-rendition-server/conf/license.xml
          subPath: license.xml
        - name: rendition-server-share
          mountPath: /opt/ceyoniq/nscale-rendition-server/work
        ports:
        - containerPort: 8192
          name: rendition
      volumes:
      - name: license
        configMap:
          name: license
      - name: rendition-server-share
        persistentVolumeClaim:
          claimName: rendition-server-share
---
apiVersion: v1
kind: Service
metadata:
  name: rendition-server
  labels:
    service: rendition-server
spec:
  ports:
  - port: 8192
    name: rendition
    appProtocol: http
  selector:
    app: rendition-server

