apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-layer
  labels:
    app: storage-layer
spec:
  serviceName: storage-layer
  selector:
    matchLabels:
      app: storage-layer
  replicas: 1
  template:
    metadata:
      labels:
        #sidecar.istio.io/inject: "false"
        app: storage-layer
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"      
    spec:
      automountServiceAccountToken: false
      initContainers:
      # The license file mount inside the conf volume prevents the volume to get initialized with the image data.
      # Therefore we need to copy the data from the image to the volume manually before startup.
      - name: storage-layer-conf
        image: ceyoniq.azurecr.io/release/nscale/storage-layer:ubi.10.0.1201.2025072114
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          # Copy the configuration from the image into the volume on first startup.
          test -f /mnt/DA_HID.DAT ||
            cp -a /opt/ceyoniq/nscale-server/storage-layer/etc/* /mnt
        volumeMounts:
        - name: storage-layer
          subPath: etc
          mountPath: /mnt
      containers:
      - name: storage-layer
        image: ceyoniq.azurecr.io/release/nscale/storage-layer:ubi.10.0.1201.2025072114
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - /opt/ceyoniq/nscale-server/storage-layer/bin/cstool
            - srv
            - -m1
            - -c
            - sock
          initialDelaySeconds: 1
          failureThreshold: 1
        env:
        - name: LOG_APPENDER
          value: "Console"
        #- name: NSTL_STORAGE-LAYER_LOGLEVEL
        #  value: "4"
        ports:
        - containerPort: 3005
          name: storage
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/etc/license.xml
        - name: storage-layer
          subPath: log
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/log
        - name: storage-layer
          subPath: ret
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/ret
        - name: storage-layer
          subPath: etc
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/etc
        - name: storage-layer
          subPath: da
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/da
        - name: storage-layer
          subPath: arc
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/arc
      #- name: prometheus-exporter
      #  image: ceyoniq.azurecr.io/release/nscale/storage-layer:ubi.10.0.1201.2025072114
      #  imagePullPolicy: Always
      #  command: 
      #  - cstool-prometheus-exporter
      #  args:
      #  - --urls 
      #  - http://::9090
      #  - --host=$(INSTANCE_NAME) 
      #  - --port=3005 
      #  - --Logging:LogLevel:Microsoft=Warning
      #  ports:
      #  - containerPort: 9090
      #    name: metrics
      #  env:
      #  - name: INSTANCE_NAME
      #    valueFrom:
      #      fieldRef:
      #        fieldPath: metadata.name
      #  resources:
      #    limits:
      #      cpu: "50m"
      #      memory: "100Mi"
      #      ephemeral-storage: "0Mi"
      #    requests:
      #      cpu: "20m"
      #      memory: "50Mi"
      #      ephemeral-storage: "0Mi"
      volumes:
      - name: license
        configMap:
          name: license
      - name: storage-layer
        persistentVolumeClaim:
          claimName: storage-layer
  volumeClaimTemplates:
  - metadata:
      name: storage-layer
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage-layer
  labels:
    app: storage-layer
spec:
  clusterIP: None
  ports:
  - port: 3005
    targetPort: 3005
    name: storage
    appProtocol: tcp
  selector:
    app: storage-layer

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storage-layer
  labels:
    app: storage-layer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: storage-layer