apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-layer
  labels:
    app: storage-layer
spec:
  serviceName: storage-layer
  selector:
    matchLabels:
      app: storage-layer
  replicas: 1
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: storage-layer
    spec:
      imagePullSecrets:
      - name: regcred    
      initContainers:
      # The license file mount inside the conf volume prevents the volume to get initialized with the image data.
      # Therefore we need to copy the data from the image to the volume manually before startup.
      - name: storage-layer-conf
        image: ceyoniq.azurecr.io/release/nscale/storage-layer:8.0.5001.2021033108.551023531334
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          # Copy the configuration from the image into the volume on first startup.
          test -f /mnt/DA_HID.DAT ||
            cp -a /opt/ceyoniq/nscale-server/storage-layer/etc/* /mnt
        volumeMounts:
        - name: storage-layer
          subPath: etc
          mountPath: /mnt
      containers:
      - name: storage-layer    
        image: ceyoniq.azurecr.io/release/nscale/storage-layer:8.0.5001.2021033108.551023531334
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/ceyoniq/nscale-server/storage-layer/bin/readiness-probe.sh
          periodSeconds: 10
        env:
        - name: LOG_APPENDER
          value: "Console"
        ports:
        - containerPort: 3005
          name: storage
        resources:
          limits:
            cpu: "2000m"
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: license
          subPath: license.xml
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/etc/license.xml
        - name: storage-layer
          subPath: etc
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/etc
        - name: storage-layer
          subPath: da
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/da
        - name: storage-layer
          subPath: arc
          mountPath: /opt/ceyoniq/nscale-server/storage-layer/arc
      volumes:
      - name: license
        configMap:
          name: storage-layer-license
      - name: storage-layer
        persistentVolumeClaim:
          claimName: storage-layer
---
apiVersion: v1
kind: Service
metadata:
  name: storage-layer
  labels:
    app: storage-layer
spec:
  ports:
  - port: 3005
    name: storage-layer
  selector:
    app: storage-layer