apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-connector
  labels:
    app: webdav-connector
spec:
  selector:
    matchLabels:
      app: webdav-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webdav-connector
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webdav-connector
        image: ceyoniq.azurecr.io/release/nscale/webdav-connector:ubi.9.0.1200.2023051702
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /dav/
#            port: 8088
#          initialDelaySeconds: 20
        env:
        - name: WEBDAV_AL_HOST
          value: "application-layer"
        - name: WEBDAV_AL_PORT
          value: "8080"
        - name: WEBDAV_AL_SSL
          value: "0"
        - name: WEBDAV_AL_INSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8088
          name: webdav
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
            ephemeral-storage: "400Mi"
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-webdav/temp
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webdav-connector
  labels:
    service: webdav-connector
spec:
  ports:
  - port: 8088
    targetPort: 8088
    name: webdav
    appProtocol: http
  selector:
    app: webdav-connector
