apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-connector
  labels:
    app: webdav-connector
spec:
  selector:
    matchLabels:
      app: webdav-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webdav-connector
    spec:
      automountServiceAccountToken: false
      containers:
      - name: webdav-connector
        image: ceyoniq.azurecr.io/release/nscale/webdav-connector:ubi.10.0.1000.2025032002
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /dav/
#            port: webdav
#          initialDelaySeconds: 20
        env:
        - name: WEBDAV_AL_HOST
          value: "application-layer"
        - name: WEBDAV_AL_PORT
          value: "8080"
        - name: WEBDAV_AL_SSL
          value: "0"
        - name: WEBDAV_AL_INSTANCE
          value: "nscalealinst1"
        - name: WEBDAV_AL_DOMAIN
          value: "nscale"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        ports:
        - containerPort: 8088
          name: webdav
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-webdav/temp
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webdav-connector
  labels:
    service: webdav-connector
spec:
  ports:
  - port: 8088
    targetPort: 8088
    name: webdav
    appProtocol: http
  selector:
    app: webdav-connector
