apiVersion: apps/v1
kind: Deployment
metadata:
  name: xta-connector
  labels:
    app: xta-connector
spec:
  selector:
    matchLabels:
      app: xta-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xta-connector
    spec:
      automountServiceAccountToken: false
      containers:
      - name: xta-connector
        image: ceyoniq.azurecr.io/release/nscale/xta-connector:ubi.9.2.1000.2024032222
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /xta/
            port: 8099
          initialDelaySeconds: 20
        env:
        - name: XTA_AL_HOST
          value: "application-layer"
        - name: XTA_AL_PORT
          value: "8080"
        - name: XTA_AL_SSL
          value: "false"
        - name: XTA_AL_INSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=50.0"
        - name: XTA_AL_DOCAREA
          value: "DA"
        - name: XTA_AL_DOMAIN
          value: "nscale"
        - name: XTA_AL_USER
          value: "admin"
        - name: XTA_AL_PASSWORD
          value: "admin"
        - name: XTA_AL_FOLDERQUERY
          value: "resourcetype=1 and displayname='XTA'"
        ports:
        - containerPort: 8099
          name: xta
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-xta-connector/temp
      volumes:
      - name: temp
        emptyDir:
          sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: xta-connector
  labels:
    service: xta-connector
spec:
  ports:
  - port: 8099
    targetPort: 8099
    name: xta
    appProtocol: http
  selector:
    app: xta-connector
