apiVersion: apps/v1
kind: Deployment
metadata:
  name: xta-connector
  labels:
    app: xta-connector
spec:
  selector:
    matchLabels:
      app: xta-connector
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xta-connector
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      containers:
      - name: xta-connector
        image: ceyoniq.azurecr.io/release/nscale/xta-connector:8.2.1000.2021110322.771183778829
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - ./liveness-probe.sh
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - ./readiness-probe.sh
        env:
        - name: XTA_AL_HOST
          value: "application-layer"
        - name: XTA_AL_PORT
          value: "8080"
        - name: XTA_AL_SSL
          value: "false"
        - name: XTA_AL_INSTANCE
          value: "nscalealinst1"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0"
        - name: XTA_AL_DOCAREA
          value: "DA"
        - name: XTA_AL_DOMAIN
          value: "nscale"
        - name: XTA_AL_USER
          value: "admin"
        - name: XTA_AL_PASSWORD
          value: "admin"
        - name: XTA_AL_FOLDERQUERY
          value: "resourcetype=1 and displayname='XTA'"
        ports:
        - containerPort: 8099
          name: xta
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
        volumeMounts:
        - name: temp
          mountPath: /opt/ceyoniq/nscale-xta-connector/temp
      volumes:
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: xta-connector
  labels:
    service: xta-connector
spec:
  ports:
  - port: 8099
    targetPort: 8099
    name: xta
  selector:
    app: xta-connector