apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator
spec:
  template:
    spec:
      containers:
      - name: administrator
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
