apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendition-server
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: rendition-server
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
