ARG baseImage=container-registry.ct.com/nscale/base/openjdk-17-runtime:latest
FROM $baseImage

USER root
RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
        jq-1.6-14.el9 \
        findutils-4.8.0-5.el9 \
  && microdnf clean all
USER default
