ARG baseImage=container-registry.ct.com/nscale/base/openjdk-17-runtime:latest
FROM $baseImage

ARG crocore_version=1.31.0
ARG crocore_package=10.el9
USER root
RUN \
    microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
      fonts-filesystem-2.0.5-7.el9.1 \
      fontconfig-2.14.0-2.el9_1 \
	&& microdnf clean all \
  # https://fedoraproject.org/wiki/Google_Croscore_fonts
  && rpm --install --noverify \
    https://kojipkgs.fedoraproject.org/packages/google-croscore-fonts/$crocore_version/$crocore_package/noarch/google-arimo-fonts-$crocore_version-$crocore_package.noarch.rpm \
  && rpm --install --noverify \
    https://kojipkgs.fedoraproject.org/packages/google-croscore-fonts/$crocore_version/$crocore_package/noarch/google-cousine-fonts-$crocore_version-$crocore_package.noarch.rpm \
  && rpm --install --noverify \
    https://kojipkgs.fedoraproject.org/packages/google-croscore-fonts/$crocore_version/$crocore_package/noarch/google-tinos-fonts-$crocore_version-$crocore_package.noarch.rpm \
  # remove default dejaVue fonts
  && rpm -e --nodeps dejavu-sans-fonts \
  # https://wiki.archlinux.org/title/font_configuration
  && fc-cache -v
USER default
