ARG baseImage=registry.source.ceyoniq.com/ceyoniq/fe/nbox/container/base/openjdk-17-runtime:latest
FROM $baseImage

USER root
RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       libxslt-1.1.34-9.el9 \
       glibc-langpack-en-2.34-83.el9_3.7 \
  && microdnf clean all

RUN \
     arch=$(rpm -q --qf "%{ARCH}" glibc) \
  && release=$(rpm -q --qf "%{RELEASE}" glibc | cut -d '_' -f 1) \
  && version=$(rpm -q --qf "%{VERSION}" glibc) \
  && rpm --install --nodeps https://kojihub.stream.centos.org/kojifiles/packages/glibc/${version}/${release}.7/${arch}/glibc-langpack-de-${version}-${release}.7.${arch}.rpm \
  && rpm --install --nodeps https://kojihub.stream.centos.org/kojifiles/packages/glibc/${version}/${release}.7/${arch}/libnsl-${version}-${release}.7.${arch}.rpm
  
USER default
