# https://catalog.redhat.com/software/containers/ubi9/nodejs-16-minimal/61a6059abfd4a5234d59621f
ARG baseImage=registry.access.redhat.com/ubi9/nodejs-16-minimal:1-116

FROM $baseImage

USER root
RUN \
     microdnf reinstall --disablerepo=* --enablerepo=ubi-* --assumeyes tzdata-2023c-1.el9 \
  && microdnf clean all
USER 1001
