# https://catalog.redhat.com/software/containers/ubi9/openjdk-17-runtime/61ee7d45384a3eb331996bee
# https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f
# https://catalog.redhat.com/en/software/containers/ubi9/openjdk-25-runtime/69204990c46419100ce30a5b
#ARG baseImage=registry.access.redhat.com/ubi9/openjdk-17-runtime:1.24-2.1773186562
#ARG baseImage=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24-2.1773186561
ARG baseImage=registry.access.redhat.com/ubi9/openjdk-25-runtime:1.24-2.1773186582

FROM $baseImage

# see https://access.redhat.com/solutions/5616681
# unzip for application-layer-web to read a plugin jar from the nappl before starting the container
USER root
RUN \
     microdnf reinstall --disablerepo=* --enablerepo=ubi-* --assumeyes tzdata-2025c-1.el9 \
  && microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       unzip-6.0-59.el9 \
  && microdnf clean all
USER default
