ARG baseImage=registry.source.ceyoniq.com/ceyoniq/fe/nbox/container/base/openjdk-17-runtime:latest
FROM $baseImage

ARG fonts_version=2.1.3-5.el9
USER root
RUN \
    microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
      fonts-filesystem-1:2.0.5-7.el9.1 \
      fontconfig-2.14.0-2.el9_1 \
	&& microdnf clean all \
  # https://en.wikipedia.org/wiki/Liberation_fonts
  && rpm --install --noverify \
    https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/l/liberation-fonts-common-${fonts_version}.noarch.rpm \
  && rpm --install --noverify \
    https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/l/liberation-mono-fonts-${fonts_version}.noarch.rpm \
  && rpm --install --noverify \
    https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/l/liberation-sans-fonts-${fonts_version}.noarch.rpm \
  && rpm --install --noverify \
    https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/l/liberation-serif-fonts-${fonts_version}.noarch.rpm \
  && rpm --install --noverify \
    https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/l/liberation-fonts-${fonts_version}.noarch.rpm \
  # remove default dejaVue fonts
  && rpm -e --nodeps dejavu-sans-fonts \
  # https://wiki.archlinux.org/title/font_configuration
  && fc-cache -v

USER default
