# https://catalog.redhat.com/software/containers/ubi9/openjdk-17-runtime/61ee7d45384a3eb331996bee
# https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f
#ARG baseImage=registry.access.redhat.com/ubi9/openjdk-17-runtime:1.23-6.1763034979
ARG baseImage=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.23-6.1763034977

FROM $baseImage

# see https://access.redhat.com/solutions/5616681
# unzip for application-layer-web to read a plugin jar from the nappl before starting the container
USER root
RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes tzdata-2025b-2.el9 \
  && microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       unzip-6.0-59.el9 \
  && microdnf clean all
USER default
