ARG baseImage=container-registry.ct.com/nscale/base/minimal:latest
FROM $baseImage

RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       procps-ng-3.3.17-11.el9 \
       shadow-utils-2:4.9-6.el9 \
  && microdnf clean all
