ARG baseImage=registry.source.ceyoniq.com/ceyoniq/fe/nbox/container/base/openjdk-17-runtime:latest
##################################################
# Compile Rendition Tools
FROM registry.access.redhat.com/ubi9/perl-532 AS dependencies

USER 0
RUN yum update --disablerepo=* --enablerepo=ubi-* --assumeyes && \
  yum install --disablerepo=* --enablerepo=ubi-* --assumeyes cpp gcc gcc-c++ make automake libtool gettext gettext-libs diffutils && \
  yum install --disablerepo=* --enablerepo=ubi-* --assumeyes libjpeg libtiff libpng libwebp giflib && \
  yum install --disablerepo=* --enablerepo=ubi-* --assumeyes nmap-ncat fontconfig vim-minimal zip bzip2

WORKDIR /tmp

RUN \
  curl -L https://github.com/ImageMagick/ImageMagick/archive/7.1.1-29.tar.gz | tar -xz && \
  cd ImageMagick-* && \
  ./configure --prefix=/opt && \
  make && \
  make install

RUN \
  curl -L https://github.com/DanBloomberg/leptonica/archive/1.84.1.tar.gz | tar -xz && \
  cd leptonica-* && \
  ./autogen.sh && \
  ./configure --prefix=/opt && \
  make && \
  make install

RUN \
  curl -L https://github.com/tesseract-ocr/tesseract/archive/5.3.4.tar.gz | tar -xz && \
  cd tesseract-* && \
  ./autogen.sh && \
  ./configure LDFLAGS="-L/opt/lib"  LEPTONICA_LIBS="-lleptonica" LEPTONICA_CFLAGS="-I/opt/include/leptonica/" --disable-legacy --prefix=/opt && \
  make && \
  make install

RUN \
  TESSDATA_PREFIX=/opt/share/tessdata && \
  mkdir -p ${TESSDATA_PREFIX} && \
  curl -L https://github.com/tesseract-ocr/tessdata_fast/raw/main/deu.traineddata -o ${TESSDATA_PREFIX}/deu.traineddata && \
  curl -L https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata -o ${TESSDATA_PREFIX}/eng.traineddata && \
  /opt/bin/tesseract --list-langs

RUN \
  curl -L https://www.ceyoniq.com/wp-content/uploads/2021/10/Delius-Logo.png -o logo.png && \
  /opt/bin/tesseract -l eng logo.png logo && \
  cat logo.txt && \
  grep DELIUS logo.txt

# TODO use v1.11
RUN \
  curl -L https://github.com/kyz/libmspack/archive/v1.5.tar.gz | tar -xz && \
  cd libmspack-1.5/cabextract/trunk && \
  autoreconf -i -W all && \
  ./configure --prefix=/opt && \
  make && \
  make install

##################################################
ARG baseImage
FROM $baseImage

COPY --from=dependencies /opt /opt

USER root
RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       jbigkit-libs-2.1-23.el9 \
       libtiff-4.4.0-12.el9 \
       libwebp-1.2.0-8.el9_3 \
       giflib-5.2.1-9.el9 \
       libgomp-11.4.1-3.el9 \
       libpng-2:1.6.37-12.el9 \
       libX11-1.7.0-9.el9 \
	&& microdnf clean all \
  # patch installation directory
  #ln -s /opt/ceyoniq/tools/bin/wkhtmltopdf /usr/bin/wkhtmltopdf \
  && ln -s /opt/bin/convert /usr/bin/convert \
  && ln -s /opt/bin/tesseract /usr/bin/tesseract \
  && mkdir -m 775 /tmp/lept
USER default
