ARG baseImage=registry.source.ceyoniq.com/ceyoniq/fe/nbox/container/base/openjdk-21-runtime:latest
FROM $baseImage

USER root
RUN \
     microdnf install --disablerepo=* --enablerepo=ubi-* --assumeyes \
       libxslt-1.1.34-13.el9_6 \
       glibc-langpack-en-2.34-168.el9_6.19 \
  && microdnf clean all

RUN \
     arch=$(rpm -q --qf "%{ARCH}" glibc) \
  && release=$(rpm -q --qf "%{RELEASE}" glibc | cut -d '_' -f 1) \
  && version=$(rpm -q --qf "%{VERSION}" glibc) \
  && rpm --install --nodeps https://kojihub.stream.centos.org/kojifiles/packages/glibc/${version}/${release}/${arch}/glibc-langpack-de-${version}-${release}.${arch}.rpm \
  && rpm --install --nodeps https://kojihub.stream.centos.org/kojifiles/packages/glibc/${version}/${release}/${arch}/libnsl-${version}-${release}.${arch}.rpm
  
USER default
