apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
spec:
  template:
    metadata:                                                                                                                                     
      annotations:                                                                                                                                                                         
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"
    spec:
      serviceAccountName: kubeapi-svc-account
      initContainers:
      - name: wait-for-database
        image: docker.io/bitnamilegacy/kubectl:1.32
        imagePullPolicy: Always
        args:
        - wait 
        - pod 
        - --for=condition=ready 
        - --selector 
        - 'app=postgresql'
        - --timeout=20s
