apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../security
- application-layer-setup.yaml
- rbac.yaml

patches:
- path: application-layer.yaml
- path: pipeliner.yaml
- target:
    kind: StatefulSet
    name: application-layer
  patch: |-
    - op: remove
      path: /spec/template/spec/automountServiceAccountToken
- target:
    kind: StatefulSet
    name: pipeliner
  patch: |-
    - op: remove
      path: /spec/template/spec/automountServiceAccountToken
