apiVersion: batch/v1
kind: Job
metadata:
  name: monitoring-console-setup
  labels:
    app: monitoring-console-setup
spec:
  template:
    metadata:
      annotations:
        #sidecar.istio.io/inject: "false"
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"
      labels:
        app: monitoring-console-setup
    spec:
      serviceAccountName: kubeapi-svc-account
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: wait-for-monitoring-console
        image: docker.io/bitnami/kubectl:1.30.1
        imagePullPolicy: Always
        args:
        - wait 
        - pod 
        - --for=condition=ready 
        - --selector 
        - 'app=monitoring-console'
        - --timeout=150s
        securityContext:
          runAsUser: 10001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: "50m"
            memory: "50Mi"
            ephemeral-storage: "0Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
            ephemeral-storage: "0Mi"
      containers:
      - name: monitoring-console
        image: ceyoniq.azurecr.io/release/nscale/monitoring-console:ubi.9.3.1000.2024092618
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - > 
          echo "initialize Monitoring";
          echo 'Application Layer Configuration=host=application-layer-0.application-layer,port=8080' >> /tmp/mc.properties;
          echo 'Application Layer=host=application-layer,port=8080' >> /tmp/mc.properties;
          echo 'Storage Layer=host=storage-layer,port=3005' >> /tmp/mc.properties;
          echo 'alw=host=application-layer-web,port=8090' >> /tmp/mc.properties;
          echo 'rendition-server=host=rendition-server,port=8192' >> /tmp/mc.properties;
          java -jar lib/mc-cmdclient.jar --host monitoring-console INITCOMPOSE admin=admin admin=admin /tmp/mc.properties || exit 1;
          echo "done";
        securityContext:
          runAsUser: 10001
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: "1000m"
            memory: "1500Mi"
            ephemeral-storage: "900Mi"
          requests:
            cpu: "100m"
            memory: "1000Mi"
            ephemeral-storage: "800Mi"
      restartPolicy: Never
  backoffLimit: 3
  #activeDeadlineSeconds: 180
