apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapi-svc-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeapi-role
rules:
- apiGroups: [""]
  resources: ["services", "pods", "jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeapi-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeapi-role
subjects:
- kind: ServiceAccount
  name: kubeapi-svc-account