apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-console-workspace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rendition-server-share
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
