# see https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-layer
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-console-workspace
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
