# https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rendition-server-share
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeliner-data
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
