---
apiVersion: batch/v1
kind: Job
metadata:
  name: application-layer-setup2
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-application-layer-and-da
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: application-layer-setup
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
