apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-layer
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
  volumeClaimTemplates:
  - metadata:
      name: storage-layer
    spec:
      storageClassName: default
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
