apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        securityContext:
          runAsUser: 10001
      containers:
      - name: application-layer
        securityContext:
          runAsUser: 10001
