apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: postgresql
        securityContext:
          runAsUser: 10001
