apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-connector
spec:
  template:
    spec:
      containers:
      - name: webdav-connector
        securityContext:
          runAsUser: 10001
