apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-layer
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: application-layer
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault

---
apiVersion: batch/v1
kind: Job
metadata:
  name: application-layer-setup
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-application-layer
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: application-layer
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
