bases:
- ../network

patchesStrategicMerge:
- postgresql.yaml
- application-layer.yaml
- storage-layer.yaml
- application-layer-web.yaml
- rendition-server.yaml
- administrator.yaml
- monitoring-console.yaml
- console.yaml
# Enable process automation modeler
#- process-automation-modeler.yaml
# Enable pipeliner
#- pipeliner.yaml
# Enable nscale connectors if required
#- cmis-connector.yaml
#- ilm-connector.yaml
#- webdav-connector.yaml
#- xta-connector.yaml
