apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pipeliner
spec:
  template:
    spec:
      containers:
      - name: pipeliner
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
