apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-automation-modeler
spec:
  template:
    spec:
      containers:
      - name: process-automation-modeler
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
