---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: administrator
spec:
  podSelector:
    matchLabels:
      app: administrator
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: nscale
