---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: application-layer-setup
spec:
  podSelector:
    matchLabels:
      app: application-layer-setup
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        # allow complete internet for demo
        cidr: "0.0.0.0/0"
    # NOTE: open necessary IPs for Kubernetes API Server (10.0.0.1), LDAP and SMTP server.
    # Kubernetes API Server
    #- ipBlock:
    #    cidr: 10.0.0.1/32
  - to:
    - podSelector:
        matchLabels:
          app: application-layer
    ports:
      - protocol: TCP
        port: 8080
