---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: application-layer-web
spec:
  podSelector:
    matchLabels:
      app: application-layer-web
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    # access from monitoring-console in the same namespace
    - podSelector:
        matchLabels:
          app: monitoring-console
    ports:
      - protocol: TCP
        port: web
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: application-layer
    ports:
      - protocol: TCP
        port: application
