---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: rendition-server
spec:
  podSelector:
    matchLabels:
      app: rendition-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: application-layer
    ports:
      - protocol: TCP
        port: 8192
