
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../runas
- ../network

patches:
- path: postgresql-volumes.yaml
  target:
    group: apps
    kind: Deployment
    name: postgresql
    version: v1
- path: monitoring-console-volumes.yaml
  target:
    group: apps
    kind: Deployment
    name: monitoring-console
    version: v1
- path: rendition-server-volumes.yaml
  target:
    group: apps
    kind: Deployment
    name: rendition-server
    version: v1
- path: storage-layer-volumes.yaml
  target:
    group: apps
    kind: StatefulSet
    name: storage-layer
    version: v1
- path: pipeliner-volumes.yaml
  target:
    group: apps
    kind: StatefulSet
    name: pipeliner
    version: v1
