---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: application-layer
spec:
  selector:
    matchLabels:
      app: application-layer
  podTargetLabels: 
  - app
  podMetricsEndpoints:
  - port: application
    path: /metrics
  - port: application
    path: /nscalealinst1/metrics

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: application-layer-monitoring
spec:
  podSelector:
    matchLabels:
      app: application-layer
  policyTypes:
  - Ingress
  ingress:
  - from:
    # access from monitoring namespace
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: application
